[build]
  command = "npm run build"
  publish = ".netlify/static"

[build.environment]
  NEXT_DISABLE_BUILD_WORKER = "1"
  NODE_OPTIONS = "--max-old-space-size=6144"

[[plugins]]
  package = "@netlify/plugin-nextjs"